
#修改服务器的端口号和上下文路径
server:
  port: 80
  servlet:
    context-path: /
#配置视图解析器
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp


#数据源：spring自带的数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javawork?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.system.entity
#分页配置
pagehelper:
  reasonable: true
